version: '3'

tasks:
  build:
    cmds:
      - go build -o tf cmd/tf/main.go
    sources:
      - ./**/*.go
    generates:
      - tf
    silent: false

  clean:
    cmds:
      - rm tf

  test:
    cmds:
      - go test neomantra/tf/internal/tf
    silent: false

  default:
    cmds:
      - task: test
      - task: build



